### PR TITLE
Gamification Dashboard

### PR DESCRIPTION
**Pull request by rickposp**
These changes are for a gamification dashboard that encourages competition between teams by comparing them based on a set of metrics.

**Configuring Hygieia for the Dashboard**
The administrator must make an API call to the new `/gamification/metrics` endpoint to initialize the metrics in the database. The endpoint is documented in Swagger. Once the metrics have been initialized, the administrator can toggle metrics and set the score ranges in the administration page.

**Configuring the Dashboard**
To populate the dashboard, the user creates a product dashboard with at least one team. Assuming the administrator has performed the configuration mentioned above, a gamification tab will appear at the top of the product dashboard page. 

**Accessing the Dashboard**
When the user clicks on the gamification tab at the top of their product dashboard, they will be presented with a bar graph and a table showing the scores for each team.

### CODE REVIEW

**Comment by rickposp** [comment]
screen shot 2017-12-04 at 9 32 42 am
screen shot 2017-12-04 at 9 32 30 am

**Comment by satishc1** [comment]
@rickposp Please rebase.

**Comment by rickposp** [comment]
I merged in the latest changes from Master to avoid modifying shared history. Let me know if you would still like me to rebase.

**Comment by rickposp** [comment]
screen shot 2017-12-20 at 10 23 15 am

**Comment by nireeshT** [comment]
@rickposp  - 

When I deselected all values in admin settings -> Manage Gamification Metrics as shown  in pic 1 
screen shot 2018-01-16 at 3 29 37 pm

will you be able to get rid of tab layout altogether and bring back product dashboard to initial state. i.e with out "dashboard" tab on top. 

screen shot 2018-01-16 at 3 26 45 pm

**Comment by Beytoven** [comment]
@nireeshT @subodhbattina @satishc1 Changes have been made to hide the tabs on the product dashboard when the gamification functionality is disabled

**Comment by nireeshT** [comment]
@satishc1 @subodhbattina @tabladrum  LGTM.

**Comment by pavan149679** [comment]
@satishc1 @nireeshT Any tentative timeframe on when these changes can be merged into master? The longer this takes, the more conflicts we need to resolve due to other changes being merged in. Thank you for your time reviewing and merging this. I will resolve the conflicts and push the changes today.

**Comment by pavan149679** [comment]
@nireeshT @satishc1 Just resolved the conflicts and updated the pull request.

**Pull request closed without merging**
