### PR TITLE
Added Multi-Bitbucket support for properties file

### PR DESCRIPTION
**Pull request by andy-scollard**
Pull Requests and Commits:
  Added Multi-Bitbucket instance support for properties file
  Added Multi-User/Password support for properties file with Base64 Encryption Required

### CODE REVIEW

**Comment by andy-scollard** [comment]
I will be on PTO until Aug 28th. I'll look at it after then if it still
remains

**Comment by rvema** [comment]
@raambabun and @andy-scollard The repository for bitbucket is now ready to be consumed from the location - https://github.com/Hygieia/hygieia-scm-bitbucket-collector. Please close this PR and create it under the new repository.

**Comment by rvema** [comment]
@andy-scollard Can you close this PR and open it against the new repository - [hygieia-scm-bitbucket-collector](https://github.com/Hygieia/hygieia-scm-bitbucket-collector) .

**Comment by rvema** [comment]
@andy-scollard I am closing this PR due to no response. Please create this under the appropriate repo as mentioned above.

**Comment by andy-scollard** [comment]
Sorry, I wasn't available. I will re-submit the PR in the new repo this week.

**Pull request closed without merging**
