### PR TITLE
Prod-setup configuration. 

### PR DESCRIPTION
**Pull request by speaktoabu**

### CODE REVIEW

**Comment by speaktoabu** [comment]
@Megha849 , can you please review it and approve

**Comment by speaktoabu** [comment]
@Megha849 @rvema @nireeshT .. Please review and approve.

**Comment by sundeepk1** [comment]
the https://hygieia.github.io/Hygieia/Prod-setup.html page is still broken it could be good if this PR can be merged . 

Also, this PR just contians info about using apache as reverse proxy, it would be good if you can also work on having nginx as one of the options

**Comment by rvema** [comment]
@speaktoabu Is this PR still work in progress? Please let us know once this is ready!

**Comment by rvema** [comment]
@speaktoabu Please respond to the above comments else we will have to close the PRs.

**Comment by rvema** [comment]
Closing this PR due to inactivity

**Pull request closed without merging**
