### PR TITLE
Angular 11 and Dashboard Changes

### PR DESCRIPTION
**Pull request by VivekBuzruk**
1] Angular 8 -> Angular 11. Apart from package.json, few config. files like angular.json are also modified.
2] Little improvement to Build, Static Code and Commit Widget appearance
3] Initial code for Product Dashboard
4] Font source downloaded and made available as part of local assets directory. This is required for internal usage within an organization.

Node version used / required : v12.13.0+

### CODE REVIEW

**Comment by rvema** [comment]
Thanks @VivekBuzruk , we will get this reviewed this week

**Comment by Sandhya-Rajasabeson** [comment]
Comparing this PR, it looks like it undoes all PRs that were merged after March 31st ie after PR #191 in the [archived UI ](https://github.com/hygieia/UI/pulls?q=is%3Apr+is%3Aclosed) Is there a reason for this? If not, please rebase accordingly and apply your changes on top of the existing project.

**Comment by VivekBuzruk** [comment]
Let me recheck, but I did merge it prior to migration.
Let me comeback by tomorrow
Sent from Yahoo Mail on Android 
 
  On Thu, Jun 10, 2021 at 9:18 PM, ***@***.***> wrote:   


Comparing this PR, it looks like it undoes all PRs that were merged after March 31st ie after PR #191 in the archived UI  Is there a reason for this? If not, please rebase accordingly and apply your changes on top of the existing project.

**Comment by VivekBuzruk** [comment]
There is definitely one mistake. Not sure how I missed (Btw. sometime back I did - git fetch upstream).

Anyway, I will create new PR after merging all my changes to master on new branch.

Thanks and sorry for the mistake

**Comment by VivekBuzruk** [comment]
Hi!

Will generate PR by tomorrow. 

One of the challenge was changes added as part of "Add dropdown to sonar widget ". Chart looses its sleekness. Also REST API ('/api/ui-widget/code-quality') mentioned in the change is not available. So, I shadowed the change through flag.

Find enclosed screenshots.

build_static_code_15_June
code_repo_15_june

**Comment by tatlax3636** [comment]
Hi @VivekBuzruk , is it okay to close this PR since the other one is now open?

**Comment by VivekBuzruk** [comment]
Updated pull request - https://github.com/hygieia/hygieia/pull/3404

**Pull request closed without merging**
