### PR TITLE
Get Karma unit tests working

### PR DESCRIPTION
**Pull request by edtan**
I noticed that the Karma unit tests weren't working, and got it updated to get the tests passing.  I did notice the new UI repo so not sure if these tests make sense to maintain, but not sure when the switch to the new repo will occur.

### CODE REVIEW

**Comment by Sbrenthughes** [comment]
The switch will not happen for a while. The angular upgrade was put on hold right now. I will review this PR shortly.

**Comment by Sbrenthughes** [comment]
Running `npm test` has some test failures for me. How are you running them?

**Comment by edtan** [comment]
I'm also running `npm test`, but it's possible that I was running those tests against a much older commit (before splitting off various components into separate repos).  I'll try again this weekend but running them against `master`.

**Comment by edtan** [comment]
It does seem to work against `master` for me.  I'm running:

```
cd UI
npm install
npm test
```

**Comment by Sbrenthughes** [comment]
Okay, looks like it may have been an environment issue. Can you update the branch so we can approve and merge?

**Comment by edtan** [comment]
I've rebased against `master` now

**Comment by Sbrenthughes** [comment]
@rvema Since i have updated this branch can you approve and merge? I approve it.

**Pull request merged**
