### PR TITLE
Avoid Spring Security to query user's groups from LDAP

### PR DESCRIPTION
**Pull request by benoitm76**
### Quick resume
Replace DefaultLdapAuthoritiesPopulator by NullLdapAuthoritiesPopulator in order to:

- Avoid unnecessary LDAP Request
- Avoid `[LDAP: error code 32 - No Such Object]` in some case (#1439)

### In details

By default, Spring Security used DefaultLdapAuthoritiesPopulator in order to collect user's groups from LDAP.

If I understand well, **admin** role in Hygieia is assigned by the database and can not be assigned using LDAP groups (no parameter to configure Groups search in the LDAP and authorities retrieved using mongo database).

Due to DefaultLdapAuthoritiesPopulator, Spring Security does a LDAP request after login to get user's groups. I have replaced it by NullLdapAuthoritiesPopulator in order to remove this unnecessary request to LDAP.

Furthermore this can cause some LDAP errors regarding to the configuration of the server: `[LDAP: error code 32 - No Such Object]` (same problem than #1439)

### CODE REVIEW

**Comment by gars01** [comment]
Great, it works

**Comment by gars01** [comment]
Thanks a lot

**Comment by rvema** [comment]
@benoitm76 We will review the changes and merge it .

**Comment by benoitm76** [comment]
I have solved conflicts due to another merge.

**Comment by benoitm76** [comment]
@rvema Unit test added ;-)

**Comment by rvema** [comment]
We will review and merge it as soon as possible

**Pull request merged**
