### PR TITLE
Feature/log analyzer

### PR DESCRIPTION
**Pull request by stevegal**
This is still WIP as I've not sanity checked end-2-end functionality yet. I'll comment when I have that checked out.

In the meantime I'd like early feedback on this PR. 

This is for #2270

### CODE REVIEW

**Comment by stevegal** [comment]
screen shot 2018-09-26 at 20 23 44
screen shot 2018-09-26 at 20 23 58
some images of what the collector looks like and its configuration screen

**Comment by rvema** [comment]
@stevegal Thanks for the PR, We will review and merge this PR.

**Comment by stevegal** [comment]
@rvema review!! yes please!!! merge? not just yet, still trying to figure out how module.js get state works so I can restore the log config dashboard!

**Comment by stevegal** [comment]
Think I've sorted it.. it appears that you need to add the `widget_state.options.id` into the config options as the field `id`. Then it works..

**Comment by stevegal** [comment]
@rvema did you get a chance to review?

**Comment by rvema** [comment]
@stevegal can you update the version of core module in collector pom.xml?

**Comment by stevegal** [comment]
@rvema done

**Comment by stevegal** [comment]
Is there any appetite for this feature?

**Comment by tabladrum** [comment]
@stevegal absolutely. This is next up in our board.

**Comment by chtompki** [comment]
Should we get these merge conflicts resolved and the feature pulled in?

**Comment by stevegal** [comment]
I can sort out the merge conflicts if this is still being considered.

**Comment by stevegal** [comment]
It’ll mostly be down to the split of the core into its own project in all likelihood

**Comment by stevegal** [comment]
now requires https://github.com/Hygieia/hygieia-core/pull/73 before building

**Pull request merged**
