### PR TITLE
Set up Jira/Feature widget through remoteCreate/remoteUpdate API

### PR DESCRIPTION
**Pull request by divashdr**
**Feature**
**Set up Jira/Feature widget creation/updation through the remoteCreate/remoteUpdate API**

Request Payload to auto created the Feature/Jira Widget is as follow

**Use Case:**
For E.g) Scrum Type

DashboardRemoteRequest request =  makeDashboardRemoteRequest(<<ADD>>);

DashboardRemoteRequest.FeatureEntry validFeature = new DashboardRemoteRequest.FeatureEntry();

        validFeature.setToolName("Jira");
        validFeature.setDescription("Metrics Service Team");
        Map<String, Object> options = new HashMap<>();
        options.put("teamName", "MST");
        options.put("featureTool", "Jira");
        options.put("projectName", "Metrics Service Team");
        options.put("projectId", "15258144130");
        options.put("teamId", "15258144034");
        options.put("estimateMetricType", "count");
        options.put("listType", "issues");
	options.put("sprintType", "scrum");

        Map<String, Object> showStatusOption = new HashMap<>();
	showStatusOption.put("kanban", false);
	showStatusOption.put("scrum", true);
	options.put("showStatus", showStatusOption);

        validFeature.setOptions(options);
        entries.add(validFeature);

        request.setFeatureEntries(entries);

### CODE REVIEW

**Comment by divashdr** [comment]
@Sbrenthughes 
As discussed, please review and merge the PR as per.

The Issue link on the discussion is
https://github.com/Hygieia/Hygieia/issues/2420

**Comment by Sbrenthughes** [comment]
Thanks for the PR we will review as soon as possible

**Comment by Sbrenthughes** [comment]
@divashdr Can you update and push again? I am hoping to get this merged this week

**Comment by divashdr** [comment]
@Sbrenthughes 
The discussion here #2420 seems to be resolved. Would you review and merge as per? Thanks

**Comment by divashdr** [comment]
The  new PR(https://github.com/Hygieia/Hygieia/pull/2580)  has incorporated the changes made as part of this particular PR.  Hence closing this.
Thanks to @Sbrenthughes & @subodhsbattina  for the support

**Pull request closed without merging**
