### PR TITLE
Docker file PROP_FILE mismatched in properties-builder

### PR DESCRIPTION
**Pull request by indrajagadeesh**
docker image is failing to find property file due to PROP_FILE mismatched

### CODE REVIEW

**Comment by rvema** [comment]
@indrajagadeesh  Please sign the CLA https://hygieia.github.io/Hygieia/contribute.html and let me know so that this PR can get merged

**Comment by rvema** [comment]
@indrajagadeesh Can you fill up the CLA form so that this change can be accepted?

**Comment by no1melman** [comment]
Do we need that test block in there? I feel like it should only be setting the PROP_FILE if it hasn't been set (and should echo a warning that it is going to change). If you need to test, just set your own PROP_FILE env prop

**Comment by rvema** [comment]
@no1melman Can you submit the PR for this change?

**Comment by no1melman** [comment]
@rvema see https://github.com/Hygieia/Hygieia/pull/3035

**Comment by rvema** [comment]
closing this PR since the user @indrajagadeesh did not sign the CLA. Please reopen once the same has been signed.

**Pull request closed without merging**
