### PR TITLE
Update pom.xml

### PR DESCRIPTION
**Pull request by riyas004**
frontend-maven-plugin  issue

### CODE REVIEW

**Comment by rvema** [comment]
@riyas004 what was the reason behind upgrading the version of frontend-maven-plugin?

**Comment by riyas004** [comment]
> 
> 
> @riyas004 what was the reason behind upgrading the version of frontend-maven-plugin?

When i install hygieia (mvn clean install package) to my system Finally getting UI error (maven frontend-plugin-0.0.29 issue, I'm just upgrade the plugin to 1.6 in inside the UI pom.xml. After I install (mvn clean install package), I didn't getting any error. That's the reason only i can update pom.xml.

**Comment by rvema** [comment]
@riyas004 testing this PR locally and once successful will merge the same.

**Comment by tabladrum** [comment]
@matthewbeasley can you check this out?

**Pull request merged**
