### PR TITLE
Remove test block from properties builder

### PR DESCRIPTION
**Pull request by no1melman**
https://github.com/Hygieia/Hygieia/issues/3026

### CODE REVIEW

**Comment by no1melman** [comment]
Have signed the the Cap One License Agreement

**Comment by rvema** [comment]
@no1melman Please sign the CLA https://hygieia.github.io/Hygieia/contribute.html and let me know so that this PR can get merged

**Comment by no1melman** [comment]
@rvema see previous comment - have done it

**Comment by rvema** [comment]
@no1melman we have migrated the jenkins collector to its own repository. We would appreciate if you could close this PR and recreate against the new repository - https://github.com/Hygieia/hygieia-build-jenkins-collector

**Pull request closed without merging**
