### PR TITLE
Changing Sonar's widget, lineCoverage to coverage

### PR DESCRIPTION
**Pull request by JULIANCHO923**
Coverage instead line coverage is better, due to coverage show us how many roads on our code logic are coverage by tests

### CODE REVIEW

**Comment by rvema** [comment]
@JULIANCHO923 Can you please confirm if you have signed the CLA? if not please sign the same - [CLA Link](http://hygieia.github.io/Hygieia/contribute.html)

**Comment by JULIANCHO923** [comment]
> @JULIANCHO923 Can you please confirm if you have signed the CLA? if not please sign the same - [CLA Link](http://hygieia.github.io/Hygieia/contribute.html)

It's done =D 👍

**Comment by JULIANCHO923** [comment]
Merging is blocked due to the idea is replace the current lines

**Comment by rvema** [comment]
@JULIANCHO923 Review is in progress and once done the change will be accepted.

**Comment by rvema** [comment]
Closing the PR due to inactivity

**Pull request closed without merging**
