### PR TITLE
Initial commit for fortify collector

### PR DESCRIPTION
**Pull request by Satheesh-Balachandran**

### CODE REVIEW

**Comment by Booma-Baskaran** [comment]
@rvema Heard that all the collectors are moving to separate repo. Can you please create a new repo for fortify collector. So, that I can raise a PR against the new repo.

**Comment by rvema** [comment]
@Booma-Baskaran Here is the link to the new repository - https://github.com/Hygieia/hygieia-codequality-fortify-collector

**Comment by Booma-Baskaran** [comment]
@rvema Thank you!!!

**Comment by rvema** [comment]
@Booma-Baskaran @Satheesh-Balachandran Do we still need this PR? now that we have a seperate repository for this collector?

**Comment by newttesting** [comment]
@rvema Sure. Thanks for merged the PR in the separate fortify repository.

**Comment by Booma-Baskaran** [comment]
@rvema Sure. Thanks for merging the changes in the separate repo.

**Comment by rvema** [comment]
closing the PR after confirmation from the creators.

**Pull request closed without merging**
