### PR TITLE
Created reportportal testresults tool collector

### PR DESCRIPTION
**Pull request by gopiprasanthpotipireddy**
reportportal.io is a test automation dashboard.

### CODE REVIEW

**Comment by rvema** [comment]
@gopiprasanthpotipireddy Please ping me on gitter, We would like this collector to go under Hygieia Organization.

**Comment by rvema** [comment]
@gopiprasanthpotipireddy we would want the collector code to go under https://github.com/Hygieia/hygieia-feature-pivotaltracker-collector. Also you would need to sign the contributors agreement, please see https://hygieia.github.io/Hygieia/contribute.html

**Comment by rvema** [comment]
@gopiprasanthpotipireddy Can you look at the comments and address them so that we can proceed with accepting your contribution? Thanks!

**Comment by gopiprasanthpotipireddy** [comment]
> @gopiprasanthpotipireddy Can you look at the comments and address them so that we can proceed with accepting your contribution? Thanks!

@rvema can you send me the gitter link so that i can ping you there.

**Comment by rvema** [comment]
@gopiprasanthpotipireddy I have sent an invite for gitter. The url for the chatroom is https://gitter.im/capitalone/Hygieia. Also please review the contributor agreement at https://hygieia.github.io/Hygieia/contribute.html

**Comment by gopiprasanthpotipireddy** [comment]
@rvema can you look into this and close once the review completed.

**Comment by rvema** [comment]
@gopiprasanthpotipireddy Did you fill up the contributor agreement? Also since this is a test automation tool I have created a new repo for the same - https://github.com/Hygieia/hygieia-codequality-pivotaltracker-collector . Please create a pull request against the new repository.

**Comment by gopiprasanthpotipireddy** [comment]
@rvema i fill up contributor agreement. but this is not pivotal tracker collector, this is reportportal collector.

**Comment by rvema** [comment]
@gopiprasanthpotipireddy Does hygieia-codequality-reportportal-collector sound good?

**Comment by gopiprasanthpotipireddy** [comment]
> @gopiprasanthpotipireddy Does hygieia-codequality-reportportal-collector sound good?

@rvema hygieia-testresults-reportportal-collector will be fine.

**Comment by rvema** [comment]
@gopiprasanthpotipireddy Test Results come under code quality hence created the repo for the same. Please close this PR and create the PR under this directory - https://github.com/Hygieia/hygieia-codequality-reportportal-collector

**Comment by gopiprasanthpotipireddy** [comment]
@rvema okay sure

**Pull request closed without merging**
