### PR TITLE
Fix/add test-data for local testing UI. Add 5 type of dashboards on gener…

### PR DESCRIPTION
**Pull request by maczernik**
Add test-data for local testing UI. Add 5 type of dashboards on general dashboard. Enable to login as admin on local testing.

All operation are possible only on run UI as 'gulp serve --local true' 

+ Add possibility to open administrator panel and watch all tabs with prepared data.  
+ Add possible ot change theme of application.
+ Add possible to open 5 type of dashboard from general dashboard. Capone, Caponechatops, Cloud, product-dashboard, splitview
+ Unlock to use most operations of Hygieia.UI.

### CODE REVIEW

**Comment by rvema** [comment]
@maczernik Thanks for your contribution, Can you confirm if you signed the [CLA](http://hygieia.github.io/Hygieia/contribute.html)? You need to sign the CLA for us the accept your changes.

**Comment by rvema** [comment]
@maczernik Can you fix the LGTM alerts introduced by this PR?

**Comment by Courtneyp123** [comment]
Hi @maczernik it is giving internal errors when navigating through admin access rights.  Also, for administering api tokens, for example, the usernames have special characters, so does not allow editing.  Could you look into this?

**Comment by Courtneyp123** [comment]
@maczernik are you available to make changes for this PR to fix the issues?

**Comment by maczernik** [comment]
I fixed the issues for LGTM but I dot have more time to implement more features for local testing :/ This PR enable to review the UI but there are a lot of work still.

**Comment by Courtneyp123** [comment]
Okay, thanks! I'm going to close the PR for now and you can open it when you are available.

**Pull request closed without merging**
