### PR TITLE
Fix GitHub spelling

### PR DESCRIPTION
**Pull request by friederbluemle**
Just a small typo fix `Github` -> `GitHub`.

### CODE REVIEW

**Comment by rvema** [comment]
Thanks for the suggestion @friederbluemle , We will review and get back to you

**Comment by friederbluemle** [comment]
Thank you @rvema

**Comment by friederbluemle** [comment]
Since it's not directly related, I opened a separate issue for the GitHub org and repo name here: https://github.com/Hygieia/Hygieia/issues/3218

**Comment by friederbluemle** [comment]
@rvema - Any chance this small PR could get merged soon?

**Comment by rvema** [comment]
verbiage changes need to be passed through a team. Can you let us know what is the change?

**Comment by friederbluemle** [comment]
Hi @rvema - Thanks for the reply. I'm not sure what you mean by "verbiage changes" .. As you can see in the diff, all this does is fix a common typo and changes `Github` to `GitHub`. Nothing else changed.
I just rebased the branch.

**Comment by rvema** [comment]
approved and merged

**Pull request merged**
